### ISSUE TITLE
[Bug] Radarr/Sonarr - HDR flowchart missing use case want 4k - SDR Only / Block HDR

### ISSUE THREAD

**Issue by bakerboy448** [TRaSH-Guides/Guides#1495]
### Guide Name

- [ ] Bazarr
- [ ] Downloaders/Deluge
- [ ] Downloaders/NZBGet
- [ ] Downloaders/Qbittorrent
- [ ] Downloaders/ruTorrent
- [ ] Downloaders/SABnzbd
- [ ] Downloaders/Other
- [ ] Guide-Sync
- [ ] Hardlinks/Docker
- [ ] Hardlinks/Dockstarter
- [ ] Hardlinks/Native
- [ ] Hardlinks/Synology
- [ ] Hardlinks/TrueNAS-Core
- [ ] Hardlinks/Unraid
- [ ] Misc
- [ ] Plex
- [ ] Prowlarr
- [X] Radarr
- [X] Sonarr
- [ ] Other

### Description

Missing usecase. Flowchart says if no DV support and no HDR and want 4K then add nothing. However this does not block 4k HDR/DV releases

### Expected Behavior

Should have usecase for those that want 4k SDR only

this would be negating all DV HDR CFs

### Additional Context

https://discord.com/channels/764440599066574859/829029163855118396/1137571961241870377

**Comment by TRaSH-** [comment]
The reason we don't cover 4k SDR is because in most cases it doesn't bring any benefits
Except that it takes up more space
The real deal breaker for 4k are the HDR formats
But if you really want 4k SDR
Then you still should add them all and score them all with -10k
Not only the DV formats

So adding 4k SDR to the flowchart would make it unnecessary complicated and in my opinion not worth the trouble for the handful of people who prefer in most cases the placebo effect.

Other issues
The sync tools need user intervention to change the scores.
Hardly any tier release groups do 4k SDR, only have seen this with a few TV shows

Solution
- Best and easiest, direct the user to 1080p.
- If the user can do HDR formats but don't mind  SDR, then they can leave out the SDR custom format, and later the files will be upgraded to releases with HDR formats.
- Create a new CF that uses a catch all for all HDR formats. Including the HDR undefined variables
